# Generated by Django 4.1.7 on 2023-03-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_post_no_of_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowersCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('following_user', models.CharField(max_length=100)),
                ('followed_user', models.CharField(max_length=100)),
            ],
        ),
    ]
